version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reviewservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - 5432:5432

  postgresqlUser:
    image: postgres
    container_name: postgresqlUser
    restart: always
    volumes:
      - postgres-data-user:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - 5433:5432

  mongo:
    image: mongo:latest
    container_name: mongodb-videometa-container
    command: mongod --auth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ../../VideoMetaService/VideoMetaService/VideoMetaService/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: VideoMetaDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Test123!

  

  # aicontentservice:
  #   build:
  #     context: ../../AiContentService/AiService/AiService

  userservice:
    build:
      context: ../../UserService/UserService/UserService
    container_name: userservice
    restart: always
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgresqlUser;Port=5432;Database=userservice;Username=postgres;Password=toor"
    ports:
      - "5047:5047"
    depends_on:
      - postgresqlUser

  reviewservice:
    build:
      context: ../../ReviewService/ReviewService/ReviewService
    container_name: reviewservice
    restart: always
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgresql;Port=5432;Database=reviewservice;Username=postgres;Password=toor"
    ports:
      - "5269:5269"
    depends_on:
      - postgresql

  videometaservice:
    build:
      context: ../../VideoMetaService/VideoMetaService/VideoMetaService
    container_name: videometaservice
    restart: always
    environment:
      MONGO_URI: mongo://admin:Test123!@mongodb-videometa-container:27017/VideoMetaDB
    ports:
      - "5175:5175"
    depends_on:
      - mongo

  blobstorageservice:
    build:
      context: ../../BlobStorageService/BlobStorageService/BlobStorageService
    container_name: blobstorageservice
    restart: always
    ports:
      - "5099:5099"
    environment:
      - BLOB_STORAGE_CONNECTION_STRING=${BLOB_STORAGE_CONNECTION_STRING}

  gatewayapi:
    build:
      context: ./ApiGateway
    container_name: gatewayapi
    restart: always
    ports:
      - "5245:5245"
    depends_on:
      - reviewservice
      - videometaservice
      - blobstorageservice

  # userservice:
  #   build:
  #     context: ../../UserService/UserService/UserService
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgresql:5432/userservice
  #   depends_on:
  #     - postgresql

volumes:
  postgres-data:
    driver: local
  postgres-data-user:
    driver: local
  mongo-data:
    driver: local

