apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-backend
  template:
    metadata:
      labels:
        app: apigateway-backend
    spec:
      containers:
        - name: apigateway-backend
          image: rikhendrix/apigateway-backend:latest
          ports:
            - containerPort: 5245
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
