apiVersion: v1
kind: Service
metadata:
  name: apigateway-backend
spec:
  type: LoadBalancer
  selector:
    app: apigateway-backend
  ports:
    - name: apigateway-backend
      protocol: TCP
      port: 80
      targetPort: 8080
