apiVersion: v1
kind: Service
metadata:
  name: apigateway-backend
spec:
  type: LoadBalancer
  selector:
    app: apigateway-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 81
      targetPort: 8081
