apiVersion: v1
kind: Service
metadata:
  name: apigateway-backend
spec:
  type: LoadBalancer
  selector:
    app: apigateway-backend
  ports:
     - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: secondary
      protocol: TCP
      port: 81
      targetPort: 8081
