name: Build and Deploy API Gateway

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Disable shallow clone to get a full clone for better analysis.

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for API Gateway
        run: dotnet restore ./ApiGateway/ApiGateway.csproj

      - name: Build API Gateway
        run: dotnet build ./ApiGateway/ApiGateway.csproj --no-restore

      # Steps for building and pushing Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ApiGateway
          file: ./ApiGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-backend:latest
